# Generated by Django 2.2.11 on 2020-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ccwOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_order_id', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('RSD', models.DateField(auto_now_add=True)),
                ('initial_term', models.IntegerField()),
                ('renewal_term', models.IntegerField()),
                ('prov_email', models.EmailField(max_length=254)),
                ('isTfEligible', models.BooleanField()),
            ],
        ),
    ]
