# Generated by Django 2.2.11 on 2020-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccworderdetails',
            name='isTfEligible',
            field=models.BooleanField(default=True),
        ),
    ]
