# Generated by Django 2.2.11 on 2020-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccw', '0002_auto_20200327_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccworderdetails',
            name='deliveryMethod',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
