# Generated by Django 2.2.11 on 2020-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccw', '0003_ccworderdetails_deliverymethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=20, unique=True)),
                ('deliveryMethod', models.CharField(max_length=10)),
            ],
        ),
    ]
