# Generated by Django 2.2.11 on 2020-03-28 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ccw', '0004_offersetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offersetup',
            name='id',
        ),
        migrations.AddField(
            model_name='offersetup',
            name='offerId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
