# Generated by Django 2.2.11 on 2020-03-29 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ccw', '0007_auto_20200328_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccworderdetails',
            name='requestedStartDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 12, 0, 18, 48550, tzinfo=utc)),
        ),
    ]
