# Generated by Django 2.2.11 on 2020-03-29 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ccw', '0009_auto_20200329_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccworderdetails',
            name='requestedStartDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 13, 4, 18, 247586, tzinfo=utc)),
        ),
    ]
